[package]
name = "formal"
version = "0.0.1"
entrypoint = "src/formal.typ"
authors = ["Vsevolod Shegolev <https://github.com/vsheg>"]
license = "MIT"
description = "A template for formal documents."
repository = "https://github.com/vsheg/formal"
compiler = "0.13.0"
exclude = ["tests", "docs", "Makefile"]
categories = ["layout", "utility"]
keywords = ["cv", "poster", "document", "academic"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = ""
